apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-springboot-umccwunp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/java-springboot-umccwunp:b5f6d75b5df1686ec8cde955d1d956257059213f@sha256:eb83885a2c2fd57ba8aac0856600f92ab556d9acba5b1849ebbad815a69c1f1b
          name: container-image
